[workspace]
members = [
    "robocode-cli",
    "robocode-config",
    "robocode-core",
    "robocode-lsp",
    "robocode-model",
    "robocode-permissions",
    "robocode-provider-deepseek",
    "robocode-provider-sdk",
    "robocode-session",
    "robocode-tools",
    "robocode-types",
    "robocode-workflows",
]
resolver = "2"

[workspace.package]
edition = "2024"
version = "0.1.18"
license = "MIT"
authors = ["wiki"]
