use std::{env, fs, path::PathBuf};

const TOKEN_SOURCE: &str = "../../docs/viden-design/Viden/tokens.css";
const REQUIRED_ROLES: [(&str, &str); 30] = [
    ("bg_void", "--bg-void"),
    ("bg_base", "--bg-base"),
    ("bg_panel", "--bg-panel"),
    ("bg_topbar", "--bg-topbar"),
    ("bg_elev", "--bg-elev"),
    ("bg_sel", "--bg-sel"),
    ("fg_primary", "--fg-primary"),
    ("fg_secondary", "--fg-secondary"),
    ("fg_muted", "--fg-muted"),
    ("fg_faint", "--fg-faint"),
    ("accent", "--accent"),
    ("accent_bright", "--accent-bright"),
    ("accent_dim", "--accent-dim"),
    ("on_accent", "--on-accent"),
    ("gold", "--gold"),
    ("gold_bright", "--gold-bright"),
    ("success", "--success"),
    ("warning", "--warning"),
    ("error", "--error"),
    ("progress", "--progress"),
    ("builtin", "--builtin"),
    ("border", "--border"),
    ("border_soft", "--border-soft"),
    ("border_active", "--border-active"),
    ("page_bg", "--page-bg"),
    ("page_card", "--page-card"),
    ("page_line", "--page-line"),
    ("page_ink", "--page-ink"),
    ("page_ink_dim", "--page-ink-dim"),
    ("page_accent", "--page-accent"),
];

const PALETTES: [(&str, &str, &str); 8] = [
    (
        "Aurora",
        "Dark",
        "[data-skin=\"aurora\"][data-mode=\"dark\"]",
    ),
    (
        "Aurora",
        "Light",
        "[data-skin=\"aurora\"][data-mode=\"light\"]",
    ),
    ("Ice", "Dark", "[data-skin=\"ice\"][data-mode=\"dark\"]"),
    ("Ice", "Light", "[data-skin=\"ice\"][data-mode=\"light\"]"),
    ("Mono", "Dark", "[data-skin=\"mono\"][data-mode=\"dark\"]"),
    ("Mono", "Light", "[data-skin=\"mono\"][data-mode=\"light\"]"),
    ("Amber", "Dark", "[data-skin=\"amber\"]"),
    ("Phosphor", "Dark", "[data-skin=\"phosphor\"]"),
];

fn main() {
    println!("cargo:rerun-if-changed={TOKEN_SOURCE}");
    let source = fs::read_to_string(TOKEN_SOURCE)
        .unwrap_or_else(|error| panic!("failed to read {TOKEN_SOURCE}: {error}"));
    let generated = generate(&source);
    let output = PathBuf::from(env::var_os("OUT_DIR").expect("Cargo sets OUT_DIR"))
        .join("appearance_tokens.rs");
    fs::write(&output, generated)
        .unwrap_or_else(|error| panic!("failed to write {}: {error}", output.display()));
}

fn generate(source: &str) -> String {
    let source = strip_css_comments(source);
    let mut generated = String::from(
        "// @generated by apps/tui/build.rs from docs/viden-design/Viden/tokens.css.\n\
         // Do not edit: change the design token source and rebuild.\n\
         pub(super) const GENERATED_PALETTES: [Palette; 8] = [\n",
    );
    for (skin, mode, selector) in PALETTES {
        let block = selector_block(&source, selector)
            .unwrap_or_else(|| panic!("missing registered palette block `{selector}`"));
        generated.push_str(&format!(
            "    Palette {{ skin: Skin::{skin}, mode: ColorMode::{mode},\n"
        ));
        for (field, token) in REQUIRED_ROLES {
            let value = declaration(block, token).unwrap_or_else(|| {
                panic!("palette {skin}/{mode} is missing required token `{token}`")
            });
            let (red, green, blue) = parse_hex(value).unwrap_or_else(|| {
                panic!("palette {skin}/{mode} token `{token}` must be a six-digit hex color, got `{value}`")
            });
            generated.push_str(&format!(
                "        {field}: Rgb::new(0x{red:02x}, 0x{green:02x}, 0x{blue:02x}),\n"
            ));
        }
        generated.push_str("    },\n");
    }
    generated.push_str("];\n");
    generated
}

fn strip_css_comments(source: &str) -> String {
    let mut stripped = String::with_capacity(source.len());
    let mut remainder = source;
    while let Some(start) = remainder.find("/*") {
        stripped.push_str(&remainder[..start]);
        let comment = &remainder[start + 2..];
        let Some(end) = comment.find("*/") else {
            return stripped;
        };
        remainder = &comment[end + 2..];
    }
    stripped.push_str(remainder);
    stripped
}

fn selector_block<'a>(source: &'a str, selector: &str) -> Option<&'a str> {
    for (offset, _) in source.match_indices(selector) {
        let after = &source[offset + selector.len()..];
        let brace = after.find('{')?;
        if !after[..brace].trim().is_empty() {
            continue;
        }
        let body = &after[brace + 1..];
        let end = body.find('}')?;
        return Some(&body[..end]);
    }
    None
}

fn declaration<'a>(block: &'a str, token: &str) -> Option<&'a str> {
    let marker = format!("{token}:");
    let start = block.find(&marker)? + marker.len();
    let value = &block[start..];
    Some(value[..value.find(';')?].trim())
}

fn parse_hex(value: &str) -> Option<(u8, u8, u8)> {
    let hex = value.strip_prefix('#')?;
    if hex.len() != 6 {
        return None;
    }
    Some((
        u8::from_str_radix(&hex[0..2], 16).ok()?,
        u8::from_str_radix(&hex[2..4], 16).ok()?,
        u8::from_str_radix(&hex[4..6], 16).ok()?,
    ))
}

#[cfg(test)]
mod tests {
    use super::generate;

    #[test]
    fn commented_out_required_token_is_treated_as_missing() {
        let source = include_str!("../../docs/viden-design/Viden/tokens.css");
        let source = source.replacen("--accent:#34bdd9;", "/* --accent:#34bdd9; */", 1);

        assert!(std::panic::catch_unwind(|| generate(&source)).is_err());
    }
}
