[package]
name = "viden-gui-spike-gpui"
version = "0.1.0-alpha.1"
edition.workspace = true
license.workspace = true

[features]
default = ["desktop"]
desktop = ["dep:gpui", "dep:gpui-component"]

[dependencies]
gpui = { version = "0.2.2", optional = true, features = ["runtime_shaders"] }
gpui-component = { version = "0.5.1", optional = true }
viden-gui-spike-common = { path = "../common" }

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"


[[bin]]
name = "viden-gui-spike-gpui"
path = "src/main.rs"
required-features = ["desktop"]
